name: CI/CD Pipeline

on:
  push:
    branches:
      - duynm810-patch-1

####################################
# 1. Generate Timestamp (dùng cho tag)
####################################
jobs:
  generate-timestamp:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.gen_timestamp.outputs.timestamp }}
    steps:
      - name: Generate Timestamp
        id: gen_timestamp
        run: echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

####################################
# 2. Define Services (tạo danh sách services)
####################################
  set-services-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Define Service Matrix
        id: set-matrix
        run: |
          MATRIX_JSON=$(cat <<EOF | jq -c .
          {
            "include": [
              {"name": "category-api", "dockerfile": "src/Services/Category/Category.Api/Dockerfile", "deployment": "deployment/kubernetes/category-api-deployment.yaml", "filterKey": "category-api"},
              {"name": "portfolio-api", "dockerfile": "src/Services/Portfolio/Portfolio.Api/Dockerfile", "deployment": "deployment/kubernetes/portfolio-api-deployment.yaml", "filterKey": "portfolio-api"},
              {"name": "ocelot-gateway", "dockerfile": "src/ApiGateways/Ocelot.Gw/Dockerfile", "deployment": "deployment/kubernetes/ocelot-gateway-deployment.yaml", "filterKey": "ocelot-gateway"},
              {"name": "web-portal", "dockerfile": "src/WebApps/UI/Portal.Web/Dockerfile", "deployment": "deployment/kubernetes/web-portal-deployment.yaml", "filterKey": "web-portal"}
            ]
          }
          EOF
          )
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT


  test-and-build:
    needs: [set-services-matrix, generate-timestamp]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.set-services-matrix.outputs.matrix) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Debug Matrix Output
        run: |
          echo "Matrix Name: ${{ matrix.name }}"
          echo "Dockerfile Path: ${{ matrix.dockerfile }}"
          echo "Deployment File: ${{ matrix.deployment }}"
          echo "Filter Key: ${{ matrix.filterKey }}"

      - name: Run Tests for ${{ matrix.name }}
        run: |
          echo "Running tests for ${{ matrix.name }}..."
